# Generated by Django 5.0 on 2023-12-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAbuObaida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=500)),
                ('question_answer', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prayermodel',
            name='image',
            field=models.ImageField(upload_to='static/imgs'),
        ),
        migrations.AlterField(
            model_name='prayermodel',
            name='month_field',
            field=models.DateField(auto_now_add=True),
        ),
    ]
