# Generated by Django 5.0 on 2023-12-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAbuObaida', '0002_questionmodel_alter_prayermodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_description', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
