# Generated by Django 5.0 on 2023-12-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAbuObaida', '0003_eventsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsmodel',
            options={'verbose_name': 'النشاطات', 'verbose_name_plural': 'النشاطات'},
        ),
        migrations.AlterModelOptions(
            name='prayermodel',
            options={'verbose_name': 'مواقيت الصلاة', 'verbose_name_plural': 'مواقيت الصلاة'},
        ),
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name': 'الأسئلة', 'verbose_name_plural': 'الأسئلة'},
        ),
        migrations.AlterField(
            model_name='prayermodel',
            name='about_mosque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
