# Generated by Django 5.0 on 2023-12-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAbuObaida', '0005_delete_prayermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_field', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='static/imgs')),
                ('about_mosque', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'مواقيت الصلاة',
                'verbose_name_plural': 'مواقيت الصلاة',
            },
        ),
    ]
